# Generated by Django 3.2.23 on 2023-11-07 12:47

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.mixins
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0023_interface_redundancy_group_data_migration'),
        ('extras', '0058_jobresult_add_time_status_idxs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('forecast_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('short_forecast', models.CharField(max_length=255)),
                ('detailed_forecast', models.TextField()),
                ('temperature', models.IntegerField()),
                ('probability_of_precipitation', models.IntegerField(default=0)),
                ('temperature_unit', models.CharField(max_length=1)),
                ('wind_speed', models.CharField(max_length=255)),
                ('wind_direction', models.CharField(max_length=2)),
                ('site', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
    ]
